// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataLayer.Views;

public partial class DataBaseContext : DbContext
{
    public DataBaseContext(DbContextOptions<DataBaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<show_count_products_in_books_and_tool> show_count_products_in_books_and_tools { get; set; }

    public virtual DbSet<show_count_products_in_category> show_count_products_in_categories { get; set; }

    public virtual DbSet<show_number_of_users_order> show_number_of_users_orders { get; set; }

    public virtual DbSet<show_top_3_product> show_top_3_products { get; set; }

    public virtual DbSet<show_top_3_users_by_number_of_order> show_top_3_users_by_number_of_orders { get; set; }

    public virtual DbSet<show_users_without_password> show_users_without_passwords { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<show_count_products_in_books_and_tool>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("show_count_products_in_books_and_tools");

            entity.Property(e => e.name).IsRequired();
        });

        modelBuilder.Entity<show_count_products_in_category>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("show_count_products_in_category");

            entity.Property(e => e.name).IsRequired();
        });

        modelBuilder.Entity<show_number_of_users_order>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("show_number_of_users_orders");

            entity.Property(e => e.login).IsRequired();
        });

        modelBuilder.Entity<show_top_3_product>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("show_top_3_products");

            entity.Property(e => e.name).IsRequired();
        });

        modelBuilder.Entity<show_top_3_users_by_number_of_order>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("show_top_3_users_by_number_of_orders");

            entity.Property(e => e.login).IsRequired();
        });

        modelBuilder.Entity<show_users_without_password>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("show_users_without_password");

            entity.Property(e => e.id).ValueGeneratedOnAdd();
            entity.Property(e => e.login).IsRequired();
            entity.Property(e => e.mail).IsRequired();
            entity.Property(e => e.name).IsRequired();
            entity.Property(e => e.registration_date).HasColumnType("datetime");
            entity.Property(e => e.surname).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}