// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Views;

public partial class show_count_products_in_category
{
    public string name { get; set; }

    public int? count_products { get; set; }
}