// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Views;

public partial class show_top_3_users_by_number_of_order
{
    public string login { get; set; }

    public int? count_orders { get; set; }
}