// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataLayer.Procedures
{
    public partial class add_categoryResult
    {
        public int id { get; set; }
        [StringLength(2147483647)]
        public string name { get; set; }
        [StringLength(2147483647)]
        public string description { get; set; }
    }
}
