// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DataLayer.Procedures;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataLayer.Procedures
{
    public partial interface IDataBaseContextProcedures
    {
        Task<int> add_admin_return_idAsync(string login, string password, string name, string surname, string patronymic, string mail, string phone_number, OutputParameter<int?> adminID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<add_categoryResult>> add_categoryAsync(string name, string description, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> add_productAsync(string name, string description, decimal? price, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> add_product_categoriesAsync(int? product_id, int? category_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> add_quantity_productAsync(int? product_id, int? warehouse_id, int? quantity, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> add_userAsync(string login, string password, string name, string surname, string patronymic, string mail, string phone_number, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> add_user_return_idAsync(string login, string password, string name, string surname, string patronymic, string mail, string phone_number, OutputParameter<int?> userID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<search_orders_by_dateResult>> search_orders_by_dateAsync(DateTime? start_date, DateTime? end_date, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<search_products_by_nameResult>> search_products_by_nameAsync(string name, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<search_products_by_priceResult>> search_products_by_priceAsync(int? start_price, int? end_price, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<show_all_productsResult>> show_all_productsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<show_products_in_categoryResult>> show_products_in_categoryAsync(int? category_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<show_products_in_portionsResult>> show_products_in_portionsAsync(int? skip_rows, int? show_rows, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_search_admin_by_idResult>> stp_search_admin_by_idAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_search_admin_for_authResult>> stp_search_admin_for_authAsync(string login, string password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_search_admin_for_infoResult>> stp_search_admin_for_infoAsync(string login, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_search_user_by_idResult>> stp_search_user_by_idAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_search_user_for_authResult>> stp_search_user_for_authAsync(string login, string password, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_search_user_for_infoResult>> stp_search_user_for_infoAsync(string login, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> stp_user_deleteAsync(int? id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> stp_user_updateAsync(int? id, string login, string password, string name, string surname, string patronymic, string mail, string phone_number, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<stp_users_allResult>> stp_users_allAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
