// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataLayer.Procedures
{
    public partial class search_products_by_nameResult
    {
        public int id { get; set; }
        [StringLength(2147483647)]
        public string name { get; set; }
        [StringLength(2147483647)]
        public string description { get; set; }
        [Column("price", TypeName = "decimal(18,2)")]
        public decimal price { get; set; }
        public DateTime? date_added { get; set; }
    }
}
