// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataLayer.Procedures
{
    public partial class stp_search_admin_by_idResult
    {
        public int id { get; set; }
        [StringLength(2147483647)]
        public string login { get; set; }
        [StringLength(2147483647)]
        public string password { get; set; }
        [StringLength(2147483647)]
        public string name { get; set; }
        [StringLength(2147483647)]
        public string surname { get; set; }
        [StringLength(2147483647)]
        public string patronymic { get; set; }
        [StringLength(2147483647)]
        public string mail { get; set; }
        [StringLength(2147483647)]
        public string phone_number { get; set; }
        public DateTime? registration_date { get; set; }
    }
}
