// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataLayer.Models;

public partial class DataBaseContext : DbContext
{
    public DataBaseContext(DbContextOptions<DataBaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<adminsSet> adminsSets { get; set; }

    public virtual DbSet<categoriesSet> categoriesSets { get; set; }

    public virtual DbSet<imagesSet> imagesSets { get; set; }

    public virtual DbSet<order_historySet> order_historySets { get; set; }

    public virtual DbSet<order_productsSet> order_productsSets { get; set; }

    public virtual DbSet<ordersSet> ordersSets { get; set; }

    public virtual DbSet<productsSet> productsSets { get; set; }

    public virtual DbSet<status_ordersSet> status_ordersSets { get; set; }

    public virtual DbSet<usersSet> usersSets { get; set; }

    public virtual DbSet<warehouse_productsSet> warehouse_productsSets { get; set; }

    public virtual DbSet<warehousesSet> warehousesSets { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<adminsSet>(entity =>
        {
            entity.ToTable("adminsSet");

            entity.HasIndex(e => e.images_id, "IX_FK_adminsimages");

            entity.Property(e => e.login).IsRequired();
            entity.Property(e => e.mail).IsRequired();
            entity.Property(e => e.name).IsRequired();
            entity.Property(e => e.registration_date).HasColumnType("datetime");
            entity.Property(e => e.surname).IsRequired();

            entity.HasOne(d => d.images).WithMany(p => p.adminsSets)
                .HasForeignKey(d => d.images_id)
                .HasConstraintName("FK_adminsimages");
        });

        modelBuilder.Entity<categoriesSet>(entity =>
        {
            entity.ToTable("categoriesSet");

            entity.Property(e => e.description).IsRequired();
            entity.Property(e => e.name).IsRequired();
        });

        modelBuilder.Entity<imagesSet>(entity =>
        {
            entity.ToTable("imagesSet");

            entity.Property(e => e.name).IsRequired();
        });

        modelBuilder.Entity<order_historySet>(entity =>
        {
            entity.ToTable("order_historySet");

            entity.HasIndex(e => e.new_status, "IX_FK_new_status");

            entity.HasIndex(e => e.old_status, "IX_FK_old_status");

            entity.HasIndex(e => e.order_id, "IX_FK_ordersorder_history");

            entity.Property(e => e.date_of_change).HasColumnType("datetime");

            entity.HasOne(d => d.new_statusNavigation).WithMany(p => p.order_historySetnew_statusNavigations)
                .HasForeignKey(d => d.new_status)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_new_status");

            entity.HasOne(d => d.old_statusNavigation).WithMany(p => p.order_historySetold_statusNavigations)
                .HasForeignKey(d => d.old_status)
                .HasConstraintName("FK_old_status");

            entity.HasOne(d => d.order).WithMany(p => p.order_historySets)
                .HasForeignKey(d => d.order_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ordersorder_history");
        });

        modelBuilder.Entity<order_productsSet>(entity =>
        {
            entity.ToTable("order_productsSet");

            entity.HasIndex(e => e.order_id, "IX_FK_ordersorder_products");

            entity.HasIndex(e => e.product_id, "IX_FK_productsorder_products");

            entity.Property(e => e.price).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.order).WithMany(p => p.order_productsSets)
                .HasForeignKey(d => d.order_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ordersorder_products");

            entity.HasOne(d => d.product).WithMany(p => p.order_productsSets)
                .HasForeignKey(d => d.product_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_productsorder_products");
        });

        modelBuilder.Entity<ordersSet>(entity =>
        {
            entity.ToTable("ordersSet");

            entity.HasIndex(e => e.status_id, "IX_FK_status_ordersorders");

            entity.HasIndex(e => e.user_id, "IX_FK_usersorders");

            entity.Property(e => e.order_placement_date).HasColumnType("datetime");
            entity.Property(e => e.total_amount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.status).WithMany(p => p.ordersSets)
                .HasForeignKey(d => d.status_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_status_ordersorders");

            entity.HasOne(d => d.user).WithMany(p => p.ordersSets)
                .HasForeignKey(d => d.user_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_usersorders");
        });

        modelBuilder.Entity<productsSet>(entity =>
        {
            entity.ToTable("productsSet");

            entity.HasIndex(e => e.images_id, "IX_FK_productsimages");

            entity.Property(e => e.date_added).HasColumnType("datetime");
            entity.Property(e => e.description).IsRequired();
            entity.Property(e => e.name).IsRequired();
            entity.Property(e => e.price).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.images).WithMany(p => p.productsSets)
                .HasForeignKey(d => d.images_id)
                .HasConstraintName("FK_productsimages");

            entity.HasMany(d => d.categories).WithMany(p => p.products)
                .UsingEntity<Dictionary<string, object>>(
                    "product_categoriesSet",
                    r => r.HasOne<categoriesSet>().WithMany()
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_categoriesproduct_categories"),
                    l => l.HasOne<productsSet>().WithMany()
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_productsproduct_categories"),
                    j =>
                    {
                        j.HasKey("product_id", "category_id");
                        j.ToTable("product_categoriesSet");
                        j.HasIndex(new[] { "category_id" }, "IX_FK_categoriesproduct_categories");
                    });
        });

        modelBuilder.Entity<status_ordersSet>(entity =>
        {
            entity.ToTable("status_ordersSet");

            entity.Property(e => e.description).IsRequired();
            entity.Property(e => e.name).IsRequired();
        });

        modelBuilder.Entity<usersSet>(entity =>
        {
            entity.ToTable("usersSet");

            entity.HasIndex(e => e.images_id, "IX_FK_usersimages");

            entity.Property(e => e.login).IsRequired();
            entity.Property(e => e.mail).IsRequired();
            entity.Property(e => e.name).IsRequired();
            entity.Property(e => e.registration_date).HasColumnType("datetime");
            entity.Property(e => e.surname).IsRequired();

            entity.HasOne(d => d.images).WithMany(p => p.usersSets)
                .HasForeignKey(d => d.images_id)
                .HasConstraintName("FK_usersimages");
        });

        modelBuilder.Entity<warehouse_productsSet>(entity =>
        {
            entity.HasKey(e => new { e.warehouse_id, e.product_id });

            entity.ToTable("warehouse_productsSet");

            entity.HasIndex(e => e.product_id, "IX_FK_productswarehouse_products");

            entity.HasOne(d => d.product).WithMany(p => p.warehouse_productsSets)
                .HasForeignKey(d => d.product_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_productswarehouse_products");

            entity.HasOne(d => d.warehouse).WithMany(p => p.warehouse_productsSets)
                .HasForeignKey(d => d.warehouse_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_warehouseswarehouse_products");
        });

        modelBuilder.Entity<warehousesSet>(entity =>
        {
            entity.ToTable("warehousesSet");

            entity.Property(e => e.description).IsRequired();
            entity.Property(e => e.name).IsRequired();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}