// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Models;

public partial class imagesSet
{
    public int id { get; set; }

    public string name { get; set; }

    public byte[] image { get; set; }

    public virtual ICollection<adminsSet> adminsSets { get; set; } = new List<adminsSet>();

    public virtual ICollection<productsSet> productsSets { get; set; } = new List<productsSet>();

    public virtual ICollection<usersSet> usersSets { get; set; } = new List<usersSet>();
}