// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Models;

public partial class order_historySet
{
    public int id { get; set; }

    public DateTime? date_of_change { get; set; }

    public string comment { get; set; }

    public int order_id { get; set; }

    public int new_status { get; set; }

    public int? old_status { get; set; }

    public virtual status_ordersSet new_statusNavigation { get; set; }

    public virtual status_ordersSet old_statusNavigation { get; set; }

    public virtual ordersSet order { get; set; }
}