// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Models;

public partial class ordersSet
{
    public int id { get; set; }

    public DateTime? order_placement_date { get; set; }

    public decimal total_amount { get; set; }

    public string address { get; set; }

    public int user_id { get; set; }

    public int status_id { get; set; }

    public virtual ICollection<order_historySet> order_historySets { get; set; } = new List<order_historySet>();

    public virtual ICollection<order_productsSet> order_productsSets { get; set; } = new List<order_productsSet>();

    public virtual status_ordersSet status { get; set; }

    public virtual usersSet user { get; set; }
}