// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Models;

public partial class order_productsSet
{
    public int id { get; set; }

    public int quantity { get; set; }

    public decimal price { get; set; }

    public int order_id { get; set; }

    public int product_id { get; set; }

    public virtual ordersSet order { get; set; }

    public virtual productsSet product { get; set; }
}