// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Models;

public partial class productsSet
{
    public int id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public decimal price { get; set; }

    public DateTime? date_added { get; set; }

    public int? images_id { get; set; }

    public virtual imagesSet images { get; set; }

    public virtual ICollection<order_productsSet> order_productsSets { get; set; } = new List<order_productsSet>();

    public virtual ICollection<warehouse_productsSet> warehouse_productsSets { get; set; } = new List<warehouse_productsSet>();

    public virtual ICollection<categoriesSet> categories { get; set; } = new List<categoriesSet>();
}