// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Models;

public partial class status_ordersSet
{
    public int id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public virtual ICollection<order_historySet> order_historySetnew_statusNavigations { get; set; } = new List<order_historySet>();

    public virtual ICollection<order_historySet> order_historySetold_statusNavigations { get; set; } = new List<order_historySet>();

    public virtual ICollection<ordersSet> ordersSets { get; set; } = new List<ordersSet>();
}