// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Models;

public partial class warehousesSet
{
    public int id { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public string address { get; set; }

    public virtual ICollection<warehouse_productsSet> warehouse_productsSets { get; set; } = new List<warehouse_productsSet>();
}