// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataLayer.Models;

public partial class warehouse_productsSet
{
    public int quantity { get; set; }

    public int warehouse_id { get; set; }

    public int product_id { get; set; }

    public virtual productsSet product { get; set; }

    public virtual warehousesSet warehouse { get; set; }
}